### ISSUE TITLE
Are current versions of canari3 and maltego4 compatible (python3)

### ISSUE THREAD

**Issue by maximlomans** [bostonlink/recon-ng-maltego#2]
i'm repackaging and profiling the whole recon-ng-maltego to be compatible with the new canari3 and maltego4 + ?  I've been having some issues packaging  (I put your name as author and email)

.local/share/virtualenvs/canari3/canari3/recon-ng-maltego/src/recon-ng-maltego# canari create-profile recon-ng-maltego
Looking for transforms in recon-ng-maltego...
Traceback (most recent call last):
  File "/home/marx/.local/share/virtualenvs/canari3/bin/canari", line 4, in <module>
    __import__('pkg_resources').run_script('canari==3.2.2', 'canari')
  File "/home/marx/.local/share/virtualenvs/canari3/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/marx/.local/share/virtualenvs/canari3/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/home/marx/.local/share/virtualenvs/canari3/lib/python2.7/site-packages/canari-3.2.2-py2.7.egg/EGG-INFO/scripts/canari", line 16, in <module>
    main()
  File "/home/marx/.local/share/virtualenvs/canari3/local/lib/python2.7/site-packages/canari-3.2.2-py2.7.egg/canari/entrypoints.py", line 44, in main
    canari_main()
  File "/home/marx/.local/share/virtualenvs/canari3/local/lib/python2.7/site-packages/canari-3.2.2-py2.7.egg/canari/commands/framework.py", line 33, in _func
    return func(self.parser.parse_args(args_, namespace))
  File "/home/marx/.local/share/virtualenvs/canari3/local/lib/python2.7/site-packages/canari-3.2.2-py2.7.egg/canari/commands/common.py", line 67, in canari_main
    opts.command_function(opts)
  File "/home/marx/.local/share/virtualenvs/canari3/local/lib/python2.7/site-packages/canari-3.2.2-py2.7.egg/canari/commands/create_profile.py", line 59, in create_profile
    transform_package = TransformDistribution(opts.package)
  File "/home/marx/.local/share/virtualenvs/canari3/local/lib/python2.7/site-packages/canari-3.2.2-py2.7.egg/canari/pkgutils/transform.py", line 73, in __init__
    (self.name, self.name, e))
ImportError: Does not appear to be a valid canari package. Couldn't import the 'recon-ng-maltego.transforms' package in 'recon-ng-maltego'. Error message: cannot import name config

**Comment by maximlomans** [comment]
Is this already packaged and built by canari or still needs to done ? cause that's what the instructions stated . The video i just opened went straight to the .config file  the .mtz is also present, of course maltego now is a few versions down the line so compatibility isn't guaranteed but man am i even more confused than ten minutes ago : (
